version: "3.9"

services:
  nginx:
    image: nginx:1.25.4
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./group-39.comp3334.xavier2dc.fr.crt:/etc/nginx/group-39.comp3334.xavier2dc.fr.crt
      - ./group-39.comp3334.xavier2dc.fr.pem:/etc/nginx/group-39.comp3334.xavier2dc.fr.pem
    depends_on:
      - webapp

  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/usr/src/app
    environment:
      - DATABASE_URL=mysql://chatuser:chatpassword@db/chatdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_DATABASE=chatdb
      - MYSQL_USER=chatuser
      - MYSQL_PASSWORD=chatpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
